Write configure script for QVDual
Enable building of QVDual in MOAB.

Minor fixes to mbchaco build.


git-svn-id: https://svn.mcs.anl.gov/repos/ITAPS/MOAB/trunk@700 6162379e-bd28-0410-9a7d-b7f4dcfcad3c

diff --git a/tools/qvdual/configure.in b/tools/qvdual/configure.in
--- a/tools/qvdual/configure.in
+++ b/tools/qvdual/configure.in
@@ -1,9 +1,9 @@
 ################################################################################
 #                           Standard Stuff
 ################################################################################
-AC_INIT(mbchaco, 0.1)
+AC_INIT(qvdual, 0.1)
 AC_CANONICAL_SYSTEM
-AM_INIT_AUTOMAKE(mbchaco,0.1)
+AM_INIT_AUTOMAKE(qvdual,0.1)
 
 AC_PROG_LN_S
 AC_PROG_MAKE_SET
@@ -233,30 +233,6 @@ AM_CONDITIONAL(NETCDF_FILE, [test "xno" != "x$NETCDF_ARG"])
 
 
 ################################################################################
-#                           Chaco
-################################################################################
-AC_ARG_WITH(chaco, 
-[AC_HELP_STRING([--with-chaco=DIR], [Specify directory containing chaco source and library])],
-[CHACO_DIR=$withval], [CHACO_DIR=])
-case "x$CHACO_DIR" in
-  xyes|xno|x)
-    AC_MSG_ERROR([--with-chaco=DIR is required])
-    ;;
-esac
-if ! test -d "$CHACO_DIR"; then
-  AC_MSG_ERROR([$CHACO_DIR : not a directory.])
-fi
-AC_CHECK_FILES([${CHACO_DIR}/code/main/defs.h ${CHACO_DIR}/code/main/params.h],
-              [], AC_MSG_ERROR([$CHACO_DIR : not a valid chaco source]))
-old_LIBS="$LIBS"
-LIBS="-L${CHACO_DIR}/code"
-AC_CHECK_LIB([chaco],[read_params],[],
-             [AC_MSG_ERROR([Could not find libchaco in ${CHACO_DIR}/code])],[-lm])
-INCLUDES="${INCLUDES} -I${CHACO_DIR}/code/main"
-LIBS="$old_LIBS -L${CHACO_DIR}/code -lchaco -lm"
-
-
-################################################################################
 #                                  MOAB
 ################################################################################
 AC_ARG_WITH(MOAB,
@@ -302,8 +278,8 @@ old_LIBS="$LIBS"
 for dir in ${MOAB_DIR}/.libs ${MOAB_DIR} ${MAOB_DIR}/lib; do
   if test "x$MOAB_LIB_DIR" = "x"; then
     LIBS="$old_LIBS -L$dir"
-    unset ac_cv_lib_MOAB_main
-    AC_CHECK_LIB([MOAB],[main],[MOAB_LIB_DIR="$dir"])
+    unset ac_cv_lib_MOAB
+    AC_HAVE_LIBRARY([MOAB],[MOAB_LIB_DIR="$dir"])
   fi
 done
 if test "x$MOAB_LIB_DIR" = "x"; then
@@ -314,6 +290,291 @@ fi
 LIBS="$old_LIBS -L$MOAB_LIB_DIR -lMOAB"
 
 AC_LANG_RESTORE
+
+
+################################################################################
+#                               GraphViz
+################################################################################
+AC_ARG_WITH([graphviz],
+[AC_HELP_STRING([--with-graphviz=DIR], [Specify directory containing GraphViz])],
+[GRAPH_DIR=$withval],[GRAPH_DIR=])
+
+case "x$GRAPH_DIR" in
+  xno)
+    AC_MSG_ERROR([Invalid option: --without-graphviz])
+    ;;
+  xyes|x)
+    GRAPH_INC_DIR=
+    GRAPH_DIR=
+    for dir in /usr /usr/local/ /; do
+      if test "x" = "x$GRAPH_DIR"; then
+        AC_CHECK_FILE([${dir}/include/graphviz/dotneato.h],[GRAPH_DIR="$dir"])
+      fi
+    done
+    AC_MSG_CHECKING([for GraphViz include dir])
+    if test "x" != x"$GRAPH_DIR"; then
+      GRAPH_INC_DIR="-I${GRAPH_DIR}/include/graphviz"
+    fi
+    AC_MSG_RESULT([$GRAPH_INC_DIR])
+    AC_MSG_CHECKING([for GraphViz library dir])
+    GRAPH_LIB_DIR=
+    for dir in ${GRAPH_DIR}/lib/graphviz /usr/lib/graphviz /usr/local/lib/graphviz /lib/graphviz; do
+      if test "x" = "x$GRAPH_LIB_DIR"; then
+        if test -d $dir; then
+          GRAPH_LIB_DIR=-L$dir
+        fi
+      fi
+    done
+    AC_MSG_RESULT([$GRAPH_LIB_DIR])
+    ;;
+  x?*)
+    GRAPH_INC_DIR=
+    for dir in ${GRAPH_DIR}/include/graphviz ${GRAPH_DIR}/include ${GRAPH_DIR}; do
+      if test "x" = "x$GRAPH_INC_DIR"; then
+        AC_CHECK_FILE([${dir}/dotneato.h],[GRAPH_INC_DIR="-I$dir"])
+      fi
+    done
+    AC_MSG_CHECKING([for GraphViz include dir])
+    if test "x" = x"$GRAPH_INC_DIR"; then
+      AC_MSG_RESULT([no])
+      AC_MSG_ERROR([Cannot find GraphViz headers in $GRAPH_DIR])
+    else
+      AC_MSG_RESULT([$GRAPH_INC_DIR])
+    fi
+    AC_MSG_CHECKING([for GraphViz library dir])
+    GRAPH_LIB_DIR=
+    for dir in ${GRAPH_DIR}/lib/graphviz ${GRAPH_DIR}/lib ${GRAPH_DIR}; do
+      if test "x" = "x$GRAPH_LIB_DIR"; then
+        if test -d $dir; then
+          GRAPH_LIB_DIR=-L$dir
+        fi
+      fi
+    done
+    if test "x" = x"$GRAPH_LIB_DIR"; then
+      AC_MSG_RESULT([no])
+      AC_MSG_ERROR([Cannot find GraphViz libraries in $GRAPH_DIR])
+    else
+      AC_MSG_RESULT([$GRAPH_LIB_DIR])
+    fi
+    ;;
+esac
+
+old_CPPFLAGS="$CPPFLAGS"
+CPPFLAGS="$CPPFLAGS $GRAPH_INC_DIR"
+AC_CHECK_HEADERS([dotneato.h],[],[AC_MSG_ERROR([Missing GraphViz header])])
+CPPFLAGS="$old_CPPFLAGS"
+INCLUDES="$INCLUDES $GRAPH_INC_DIR"
+
+LIBS="$LIBS $GRAPH_LIB_DIR"
+AC_CHECK_LIB([graph],[aginitlib],[],[AC_MSG_ERROR([Cannot find GraphViz library: -lgraph])])
+AC_CHECK_LIB([dotneato],[gvContext],[],[AC_MSG_ERROR([Cannot find GraphViz library: -ldotneato])],[-lgraph])
+LIBS="$LIBS -ldotneato -lgraph"
+
+
+################################################################################
+#                                   X
+################################################################################
+AC_PATH_X
+AC_PATH_XTRA
+if test "xyes" = "x$no_x"; then
+  AC_MSG_ERROR([Cannot build qvdual without X])
+fi
+
+
+################################################################################
+#                                  VTK
+################################################################################
+AC_LANG_SAVE
+AC_LANG_CPLUSPLUS
+
+AC_ARG_WITH([vtk],
+[AC_HELP_STRING([--with-vtk=DIR], [Specify directory containing VTK])],
+[VTK_DIR=$withval],[VTK_DIR=])
+
+case "x$VTK_DIR" in
+  xno)
+    AC_MSG_ERROR([Invalid option: --without-vtk])
+    ;;
+  xyes|x)
+    VTK_LIB_DIR=
+    VTK_INC_DIR=
+    for dir in /usr/include/vtk /usr/local/include/vtk /include/vtk; do
+      if test "x" = "x$VTK_INC_DIR"; then
+        AC_CHECK_FILE([${dir}/vtkRenderer.h],[VTK_INC_DIR="$dir"])
+      fi
+    done
+    if test x = x"$VTK_INC_DIR"; then
+      AC_CHECK_HEADER([vtkRenderer.h],[],
+                      [AC_MSG_ERROR("Could not find VTK header 'vtkRenderer.h'")])
+    else
+      INCLUDES="$INCLUDES -I$VTK_INC_DIR"
+    fi
+    ;;
+  x?*)
+    for dir in ${VTK_DIR}/include/vtk ${VTK_DIR}/include ${VTK_DIR}; do
+      if test "x" = "x$VTK_INC_DIR"; then
+        AC_CHECK_FILE([${dir}/vtkRenderer.h],[VTK_INC_DIR="$dir"])
+      fi
+    done
+    if test "x" = "x$VTK_INC_DIR"; then
+      AC_MSG_ERROR("Could not find vtkRenderer.h in $VTK_DIR")
+    fi
+    INCLUDES="$INCLUDES -I$VTK_INC_DIR"
+    old_LIBS="$LIBS"
+    for dir in ${VTK_DIR}/lib/vtk ${VTK_DIR}/lib ${VTK_DIR}; do
+      if test "x" = "x$VTK_LIB_DIR"; then
+        LIBS="$old_LIBS -L$dir"
+        unset ac_cv_lib_vtkexpat
+        AC_HAVE_LIBRARY([vtkexpat],[VTK_LIB_DIR="-L$dir"])
+      fi
+    done
+    if test "x" = "x$VTK_LIB_DIR"; then
+      AC_MSG_ERROR([Could not find vtkexpat in $VTK_DIR])
+    fi
+    LIBS="$old_LIBS"
+    ;;
+esac
+
+dnl Define a function that checks for the existence of a library
+dnl and if it exists, prepends the corresponding link flag to a 
+dnl sepecified variable
+dnl Arguments:
+dnl  - The library name
+dnl  - The name of the variable to which to prepend the library link flag
+dnl  - List of extra libraries required for link test
+dnl  - Optional library path linker argument (e.g. -L/opt/foo)
+AC_DEFUN([SNL_CHECK_LIB_LIST],[
+  old_LIBS="$LIBS"
+  LIBS="$4 ${$2} $old_LIBS"
+  AC_HAVE_LIBRARY([$1],[$2="-l$1 ${$2}"],[],[$3])
+  LIBS="$old_LIBS"
+])
+
+ # These are ordered such that a given library depends only on those libraries
+ # that preceed it in the list.
+SNL_CHECK_LIB_LIST([pthread],[vtk_sys_libs])
+SNL_CHECK_LIB_LIST([dl],     [vtk_sys_libs])
+SNL_CHECK_LIB_LIST([m],      [vtk_sys_libs])
+SNL_CHECK_LIB_LIST([gcc],    [vtk_sys_libs])
+x_libs_arg="$X_EXTRA_LIBS -lX11 $X_PRE_LIBS"
+SNL_CHECK_LIB_LIST([Xext],[vtk_x_libs],[$x_libs_arg],[-L$x_libraries]) 
+SNL_CHECK_LIB_LIST([ICE], [vtk_x_libs],[$x_libs_arg],[-L$x_libraries]) 
+SNL_CHECK_LIB_LIST([SM],  [vtk_x_libs],[$x_libs_arg],[-L$x_libraries]) 
+SNL_CHECK_LIB_LIST([Xt],  [vtk_x_libs],[$x_libs_arg],[-L$x_libraries]) 
+SNL_CHECK_LIB_LIST([GL],  [vtk_x_libs],[$x_libs_arg],[-L$x_libraries]) 
+SNL_CHECK_LIB_LIST([GLU], [vtk_x_libs],[$x_libs_arg],[-L$x_libraries]) 
+vtk_libs_arg="-L$x_libraries $vtk_x_libs $X_EXTRA_LIBS -lX11 $X_PRE_LIBS $vtk_sys_libs"
+SNL_CHECK_LIB_LIST([vtkCommon],     [vtk_libs],[$vtk_libs_arg],[$VTK_LIB_DIR])
+SNL_CHECK_LIB_LIST([vtkDICOMParser],[vtk_libs],[$vtk_libs_arg],[$VTK_LIB_DIR])
+SNL_CHECK_LIB_LIST([vtkfreetype],   [vtk_libs],[$vtk_libs_arg],[$VTK_LIB_DIR])
+SNL_CHECK_LIB_LIST([vtkexpat],      [vtk_libs],[$vtk_libs_arg],[$VTK_LIB_DIR])
+SNL_CHECK_LIB_LIST([vtkzlib],       [vtk_libs],[$vtk_libs_arg],[$VTK_LIB_DIR])
+SNL_CHECK_LIB_LIST([vtkpng],        [vtk_libs],[$vtk_libs_arg],[$VTK_LIB_DIR])
+SNL_CHECK_LIB_LIST([vtkjpeg],       [vtk_libs],[$vtk_libs_arg],[$VTK_LIB_DIR])
+SNL_CHECK_LIB_LIST([vtktiff],       [vtk_libs],[$vtk_libs_arg],[$VTK_LIB_DIR])
+SNL_CHECK_LIB_LIST([vtkftgl],       [vtk_libs],[$vtk_libs_arg],[$VTK_LIB_DIR])
+SNL_CHECK_LIB_LIST([vtkFiltering],  [vtk_libs],[$vtk_libs_arg],[$VTK_LIB_DIR])
+SNL_CHECK_LIB_LIST([vtkImaging],    [vtk_libs],[$vtk_libs_arg],[$VTK_LIB_DIR])
+SNL_CHECK_LIB_LIST([vtkGraphics],   [vtk_libs],[$vtk_libs_arg],[$VTK_LIB_DIR])
+SNL_CHECK_LIB_LIST([vtkIO],         [vtk_libs],[$vtk_libs_arg],[$VTK_LIB_DIR])
+SNL_CHECK_LIB_LIST([vtkRendering],  [vtk_libs],[$vtk_libs_arg],[$VTK_LIB_DIR])
+
+ # Make sure we found at least vtkCommon and vtkRendering
+if ! echo "x $vtk_libs" | grep lvtkCommon >/dev/null; then
+  AC_MSG_ERROR("VTK library 'vtkCommon' not found.")
+fi
+if ! echo "x $vtk_libs" | grep lvtkRendering >/dev/null; then
+  AC_MSG_ERROR("VTK library 'vtkRendering' not found.")
+fi
+
+AC_LANG_RESTORE
+
+
+################################################################################
+#                                   QT
+################################################################################
+AC_LANG_SAVE
+AC_LANG_CPLUSPLUS
+AC_ARG_VAR([QTDIR],[QT installation directory])
+if test x"$QTDIR" = x; then
+  search_path="$PATH"
+  libdir=
+  incdir=
+  for dir in /usr/include/qt3 /usr/local/include/qt3 /include/qt3; do
+    if test x = x${incdir}; then
+      if test -d $dir; then
+        incdir=-I$dir
+      fi
+    fi
+  done
+else
+  search_path="${QTDIR}/bin"
+  libdir="-L${QTDIR}/lib"
+  incdir="-I${QTDIR}/include"
+fi
+
+AC_PATH_PROG([MOC],[moc],[],[$search_path])
+if test x = x"$MOC";then
+  echo "Cannot find moc (Qt meta object compiler)"
+fi
+AC_SUBST(MOC)
+AC_PATH_PROG([UIC],[uic],[],[$search_path])
+if test x = x"$UIC";then
+  echo "Cannot find uic (Qt user interface compiler)"
+fi
+AC_SUBST(UIC)
+
+old_CXXFLAGS="$CXXFLAGS"
+old_CPPFLAGS="$CPPFLAGS"
+CXXFLAGS="$incdir"
+CPPFLAGS="$incdir"
+AC_CHECK_HEADERS([qlineedit.h qevent.h qapplication.h \
+                  qwidget.h qtimer.h qpixmap.h qwidgetplugin.h \
+                  qobject.h qmetaobject.h],[],
+                 [AC_MSG_ERROR([Required QT header not found])])
+CXXFLAGS="$old_CXXFLAGS"
+CPPFLAGS="$old_CPPFLAGS"
+INCLUDES="$incdir $INCLUDES"
+
+LIBS="$LIBS $libdir"
+# Cannot use AC_HAVE_LIBRARY for qt-mt because of
+# autoconf bug with libraries that have a '-' in their name.
+#AC_HAVE_LIBRARY([qt-mt],[LIBS="$LIBS -lqt-mt"],[
+AC_MSG_CHECKING([for main in -lqt-mt])
+old_LIBS="$LIBS"
+LIBS="$LIBS -lqt-mt"
+AC_TRY_LINK_FUNC(main,[AC_MSG_RESULT([yes])],[
+  AC_MSG_RESULT([no])
+  LIBS="$old_LIBS"
+  AC_HAVE_LIBRARY([qt],[LIBS="$LIBS -lqt"],[
+    AC_MSG_ERROR([Cannot find QT library])
+  ])
+])
+
+################################################################################
+#                                 X/VTK/QT
+################################################################################
+dnl Merge lists of libraries
+dnl Arguments
+dnl  - name of output variable
+dnl  - first list
+dnl  - second list
+AC_DEFUN([SNL_MERGE_LISTS],[
+  $1="$2"
+  # Reverse list two
+  for item3 in $3; do 
+    found=no
+    for item2 in $2; do
+      if test "x$item2" = "x$item3"; then found=yes; fi
+    done
+    if test "$found" = "no"; then $1="${$1} $item3"; fi
+  done
+  $1="${$1} $2"
+])
+SNL_MERGE_LISTS([XLIBS],[$X_EXTRA_LIBS -lX11 $X_PRE_LIBS],[$vtk_x_libs])
+SNL_MERGE_LISTS([XLIBS_tmp],[$QT_LIBS],[$XLIBS])
+SNL_MERGE_LISTS([XLIBS],[$vtk_sys_libs],[$XLIBS_tmp])
+LIBS="$LIBS $vtk_libs $XLIBS"
 
 
 ################################################################################
